import Head from "next/head";
import supabase from "../utils/supabase";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className=" text-green-900 text-3xl text-center lg:text-6xl">
          Welcome to NextJs
        </h1>
      </main>
    </>
  );
}

export async function getServerSideProps() {
  const { data: donors, error } = await supabase.from("donors").select("*");

  if (error) {
    throw new Error(error.message);
  }

  return {
    props: {
      donors,
    },
  };
}
